include(cmake_test/cmake_test)

ct_add_test("cpp_class")
    include(cmakepp_core/class/class)

    ct_add_section("Adds class if it does not exist")
        cpp_class(MyFirstClass Base1 Base2)
        _cpp_class_ctor(corr MyFirstClass Base1 Base2)
        _cpp_get_class_registry(registry)
        cpp_map(GET added_class "${registry}" MyFirstClass)
        cpp_are_equal(result "${added_class}" "${corr}")
        ct_assert_equal(result TRUE)
    ct_end_section()

    ct_add_section("Stops reading file if class exists")
            cpp_class(MyFirstClass)
            cpp_class(MyFirstClass)
            message(FATAL_ERROR "Should not get here")
    ct_end_section()
ct_end_test()
