include_guard()
include(cmakepp_core/asserts/signature)
include(cmakepp_core/object/detail_/add_fxn)
include(cmakepp_core/object/detail_/get_overloads)
include(cmakepp_core/object/detail_/get_type)
include(cmakepp_core/object/detail_/mangle_fxn)
include(cmakepp_core/utilities/return)

function(_cpp_object_add_overload _coao_obj _coao_fxn)
    cpp_assert_signature("${ARGV}" obj desc args)

    _cpp_object_add_fxn("${_coao_obj}" "${_coao_fxn}")
    _cpp_object_get_overloads(_coao_overloads "${_coao_obj}" "${_coao_fxn}")
    _cpp_object_get_type(_coao_type "${_coao_obj}")

    _cpp_mangle_fxn("${_coao_fxn}" "${_coao_fxn}" "${_coao_type}" ${ARGN})
    cpp_array(CTOR _coao_args ${ARGN})
    cpp_map(SET "${_coao_overloads}" "${_coao_args}" "${${_coao_fxn}}")
    cpp_return("${_coao_fxn}")
endfunction()
