include_guard()
include(cmakepp_core/asserts/signature)
include(cmakepp_core/map/map)
include(cmakepp_core/utilities/unique_id)

function(_cpp_object_ctor _cocn_result)
    cpp_assert_signature("${ARGV}" desc)
    cpp_unique_id("${_coc_result}")
    cpp_map(CTOR _coc_map)

    set_property(GLOBAL PROPERTY "${${_coc_result}}" "${_coc_map}")
    set_property(GLOBAL PROPERTY "${${_coc_result}}_type" object)

    cpp_map(SET "${_coc_map}" __src_file "${CMAKE_CURRENT_LIST_FILE}")
    cpp_map(SET "${_coc_map}" __my_type object)
    cpp_array(CTOR _coc_bases object)
    cpp_map(SET "${_coc_map}" __bases "${_coc_bases_object}")
    cpp_array(CTOR _coc_fxns)
    cpp_map(SET "${_coc_map}" __fxns "${_coc_fxns}")
    cpp_map(CTOR _coc_attr)
    cpp_map(SET "${_coc_map}" __attr "${_coc_attr}")
endfunction()
