include(cmake_test/cmake_test)

ct_add_test(NAME "test_cpp_is_int")
function("${test_cpp_is_int}")
    include(cmakepp_lang/types/int)

    ct_add_section(NAME "test_signature" EXPECTFAIL)
    function("${test_signature}")
        cpp_is_int(return 1 hello)
    endfunction()

    ct_add_section(NAME "test_bool")
    function("${test_bool}")
        cpp_is_int(return TRUE)
        ct_assert_equal(return FALSE)
    endfunction()

    ct_add_section(NAME "test_class")
    function("${test_class}")
        include(cmakepp_lang/class/class)
        cpp_class(MyClass)

        cpp_is_int(return MyClass)
        ct_assert_equal(return FALSE)
    endfunction()

    ct_add_section(NAME "test_command")
    function("${test_command}")
        cpp_is_int(return add_subdirectory)
        ct_assert_equal(return FALSE)
    endfunction()

    ct_add_section(NAME "test_descriptions")
    function("${test_descriptions}")
        ct_add_section(NAME "description_without_integer")
        function("${description_without_integer}")
            cpp_is_int(return "Hello World")
            ct_assert_equal(return FALSE)
        endfunction()

        ct_add_section(NAME "description_contains_integer")
        function("${description_contains_integer}")
            cpp_is_int(return "Hello World 1")
            ct_assert_equal(return FALSE)
        endfunction()
    endfunction()

    ct_add_section(NAME "test_float")
    function("${test_float}")
        cpp_is_int(return 3.14)
        ct_assert_equal(return FALSE)
    endfunction()

    ct_add_section(NAME "test_integer")
    function("${test_integer}")
        ct_add_section(NAME "small_positive")
        function("${small_positive}")
            cpp_is_int(return 42)
            ct_assert_equal(return TRUE)
        endfunction()

        ct_add_section(NAME "small_negative")
        function("${small_negative}")
            cpp_is_int(return -42)
            ct_assert_equal(return TRUE)
        endfunction()

        ct_add_section(NAME "large_positive")
        function("${large_positive}")
            cpp_is_int(return 123456789)
            ct_assert_equal(return TRUE)
        endfunction()

        ct_add_section(NAME "large_negative")
        function("${large_negative}")
            cpp_is_int(return -123456789)
            ct_assert_equal(return TRUE)
        endfunction()
    endfunction()

    ct_add_section(NAME "test_list")
    function("${test_list}")
        ct_add_section(NAME "normal_list")
        function("${normal_list}")
            cpp_is_int(return "hello;world")
            ct_assert_equal(return FALSE)
        endfunction()

        ct_add_section(NAME "list_of_integers")
        function("${list_of_integers}")
            cpp_is_int(return "1;2;3")
            ct_assert_equal(return FALSE)
        endfunction()
    endfunction()

    ct_add_section(NAME "test_map")
    function("${test_map}")
        include(cmakepp_lang/map/map)
        cpp_map(CTOR a_map)
        cpp_is_int(result a_map)
        ct_assert_equal(result FALSE)
    endfunction()

    ct_add_section(NAME "test_obj")
    function("${test_obj}")
        include(cmakepp_lang/object/object)
        cpp_is_int(result "${__CMAKEPP_LANG_OBJECT_SINGLETON__}")
        ct_assert_equal(result FALSE)
    endfunction()

    ct_add_section(NAME "test_path")
    function("${test_path}")
        ct_add_section(NAME "normal_path")
        function("${normal_path}")
            cpp_is_int(return "${CMAKE_CURRENT_LIST_DIR}")
            ct_assert_equal(return FALSE)
        endfunction()

        ct_add_section(NAME "path_contains_int")
        function("${path_contains_int}")
            cpp_is_int(return "${CMAKE_CURRENT_LIST_DIR}/3")
            ct_assert_equal(return FALSE)
        endfunction()
    endfunction()

    ct_add_section(NAME "test_target")
    function("${test_target}")
        ct_add_section(NAME "normal_target_name")
        function("${normal_target_name}")
            add_library(lib STATIC IMPORTED)
            cpp_is_int(return lib)
            ct_assert_equal(return FALSE)
        endfunction()

        ct_add_section(NAME "target_with_integer")
        function("${target_with_integer}")
            add_library(lib1 STATIC IMPORTED)
            cpp_is_int(return lib1)
            ct_assert_equal(return FALSE)
        endfunction()
    endfunction()

    ct_add_section(NAME "test_type")
    function("${test_type}")
        cpp_is_int(return bool)
        ct_assert_equal(return FALSE)
    endfunction()
endfunction()
