include(cmake_test/cmake_test)

ct_add_test(NAME [[test_cpp_is_target]])
function("${CMAKETEST_TEST}")
    include(cmakepp_lang/types/target)

    ct_add_section(NAME [[test_signature]] EXPECTFAIL)
    function("${CMAKETEST_SECTION}")
        cpp_is_target(return TRUE hello)
    endfunction()

    ct_add_section(NAME [[test_bool]])
    function("${CMAKETEST_SECTION}")
        cpp_is_target(return TRUE)
        ct_assert_equal(return FALSE)
    endfunction()

    ct_add_section(NAME [[test_class]])
    function("${CMAKETEST_SECTION}")
        include(cmakepp_lang/class/class)
        cpp_class(MyClass)

        cpp_is_target(return MyClass)
        ct_assert_equal(return FALSE)
    endfunction()

    ct_add_section(NAME [[test_command]])
    function("${CMAKETEST_SECTION}")
        cpp_is_target(return add_subdirectory)
        ct_assert_equal(return FALSE)
    endfunction()

    ct_add_section(NAME [[test_descriptions]])
    function("${CMAKETEST_SECTION}")
        ct_add_section(NAME [[description_without_target]])
        function("${CMAKETEST_SECTION}")
            cpp_is_target(return "Hello World")
            ct_assert_equal(return FALSE)
        endfunction()

        ct_add_section(NAME [[description_contains_target]])
        function("${CMAKETEST_SECTION}")
            add_library(lib STATIC IMPORTED)
            cpp_is_target(return "lib Hello World")
            ct_assert_equal(return FALSE)
        endfunction()
    endfunction()

    ct_add_section(NAME [[test_float]])
    function("${CMAKETEST_SECTION}")
        cpp_is_target(return 3.14)
        ct_assert_equal(return FALSE)
    endfunction()

    ct_add_section(NAME [[test_integer]])
    function("${CMAKETEST_SECTION}")
        cpp_is_target(return 42)
        ct_assert_equal(return FALSE)
    endfunction()

    ct_add_section(NAME [[test_list]])
    function("${CMAKETEST_SECTION}")
        ct_add_section(NAME [[normal_list]])
        function("${CMAKETEST_SECTION}")
            cpp_is_target(return "hello;world")
            ct_assert_equal(return FALSE)
        endfunction()

        ct_add_section(NAME [[list_of_targets]])
        function("${CMAKETEST_SECTION}")
            add_library(lib1 STATIC IMPORTED)
            add_library(lib2 STATIC IMPORTED)
            cpp_is_target(return "lib1;lib2")
            ct_assert_equal(return FALSE)
        endfunction()
    endfunction()

    ct_add_section(NAME [[test_map]])
    function("${CMAKETEST_SECTION}")
        include(cmakepp_lang/map/map)
        cpp_map(CTOR a_map)
        cpp_is_target(result a_map)
        ct_assert_equal(result FALSE)
    endfunction()

    ct_add_section(NAME [[test_obj]])
    function("${CMAKETEST_SECTION}")
        include(cmakepp_lang/object/object)
        cpp_is_target(result "${__CMAKEPP_LANG_OBJECT_SINGLETON__}")
        ct_assert_equal(result FALSE)
    endfunction()

    ct_add_section(NAME [[test_path]])
    function("${CMAKETEST_SECTION}")
        ct_add_section(NAME [[normal_filepath]])
        function("${CMAKETEST_SECTION}")
            cpp_is_target(return "${CMAKE_CURRENT_LIST_DIR}")
            ct_assert_equal(return FALSE)
        endfunction()

        ct_add_section(NAME [[contains_target]])
        function("${CMAKETEST_SECTION}")
            add_library(lib3 STATIC IMPORTED)
            cpp_is_target(return "${CMAKE_CURRENT_LIST_DIR}/lib3")
            ct_assert_equal(return FALSE)
        endfunction()
    endfunction()

    ct_add_section(NAME [[test_target]])
    function("${CMAKETEST_SECTION}")
        add_library(lib4 STATIC IMPORTED)
        cpp_is_target(return lib4)
        ct_assert_equal(return TRUE)
    endfunction()

    ct_add_section(NAME [[test_type]])
    function("${CMAKETEST_SECTION}")
        cpp_is_target(return bool)
        ct_assert_equal(return FALSE)
    endfunction()
endfunction()
