include(cmake_test/cmake_test)

ct_add_test("_cpp_is_array")
    include(cmakepp_core/array/detail_/ctor)
    include(cmakepp_core/types/detail_/array)

    ct_add_section("array")
        _cpp_array_ctor(my_array)
        _cpp_is_array(result "${my_array}")
        ct_assert_equal(result TRUE)
    ct_end_section()

    ct_add_section("bool")
        _cpp_is_array(return TRUE)
        ct_assert_equal(return FALSE)
    ct_end_section()

    ct_add_section("description")
        _cpp_is_array(return "Hello World")
        ct_assert_equal(return FALSE)
    ct_end_section()

    ct_add_section("filepath")
        _cpp_is_array(return "${CMAKE_CURRENT_LIST_DIR}")
        ct_assert_equal(return FALSE)
    ct_end_section()

    ct_add_section("float")
        _cpp_is_array(return 3.14)
        ct_assert_equal(return FALSE)
    ct_end_section()

    ct_add_section("integer")
        _cpp_is_array(return 42)
        ct_assert_equal(return FALSE)
    ct_end_section()

    ct_add_section("list")
        ct_add_section("Normal list")
            _cpp_is_array(return "hello;world")
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("List of arrays")
            _cpp_array_ctor(my_array)
            _cpp_is_array(return "${my_array};${my_array}")
            ct_assert_equal(return FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("map")
        include(cmakepp_core/map/detail_/ctor)
        _cpp_map_ctor(my_map)
        _cpp_is_array(result "${my_map}")
        ct_assert_equal(result FALSE)
    ct_end_section()

    ct_add_section("target")
        add_library(lib STATIC IMPORTED)
        _cpp_is_array(return lib)
        ct_assert_equal(return FALSE)
    ct_end_section()

    ct_add_section("type")
        _cpp_is_array(return bool)
        ct_assert_equal(return FALSE)
    ct_end_section()
ct_end_test()
