include(cmake_test/cmake_test)

ct_add_test("_cpp_is_bool")
    include(cmakepp_core/types/detail_/bool)

    ct_add_section("array")
        include(cmakepp_core/array/detail_/ctor)
        _cpp_array_ctor(my_array)
        _cpp_is_bool(result "${my_array}")
        ct_assert_equal(result FALSE)
    ct_end_section()

    ct_add_section("bool")
        ct_add_section("Is case-insensitive")
            _cpp_is_bool(return TrUe)
            ct_assert_equal(return TRUE)
        ct_end_section()

        ct_add_section("ON")
            _cpp_is_bool(return ON)
            ct_assert_equal(return TRUE)
        ct_end_section()

        ct_add_section("YES")
            _cpp_is_bool(return YES)
            ct_assert_equal(return TRUE)
        ct_end_section()

        ct_add_section("TRUE")
            _cpp_is_bool(return TRUE)
            ct_assert_equal(return TRUE)
        ct_end_section()

        ct_add_section("Y")
            _cpp_is_bool(return Y)
            ct_assert_equal(return TRUE)
        ct_end_section()

        ct_add_section("OFF")
            _cpp_is_bool(return OFF)
            ct_assert_equal(return TRUE)
        ct_end_section()

        ct_add_section("NO")
            _cpp_is_bool(return NO)
            ct_assert_equal(return TRUE)
        ct_end_section()

        ct_add_section("FALSE")
            _cpp_is_bool(return FALSE)
            ct_assert_equal(return TRUE)
        ct_end_section()

        ct_add_section("N")
            _cpp_is_bool(return N)
            ct_assert_equal(return TRUE)
        ct_end_section()

        ct_add_section("NOTFOUND")
            _cpp_is_bool(return NOTFOUND)
            ct_assert_equal(return TRUE)
        ct_end_section()
    ct_end_section()  # add_section(bool)

    ct_add_section("descriptions")
        ct_add_section("description w/o a bool")
            _cpp_is_bool(return "Hello World")
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("description containing a bool")
            _cpp_is_bool(return "Hello World TRUE")
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("bool with whitespace")
            _cpp_is_bool(return " TRUE")
            ct_assert_equal(return FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("filepath")
        ct_add_section("Normal filepath (probably)")
            _cpp_is_bool(return "${CMAKE_CURRENT_LIST_DIR}")
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("Contains a bool literal")
            _cpp_is_bool(return "${CMAKE_CURRENT_LIST_DIR}/TRUE")
            ct_assert_equal(return FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("float")
        _cpp_is_bool(return 3.14)
        ct_assert_equal(return FALSE)
    ct_end_section()

    ct_add_section("integer")
        ct_add_section("Traditional integer representation of true")
            _cpp_is_bool(return 1)
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("Traditional integer representation of false")
            _cpp_is_bool(return 0)
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("Not traditionally associated with true or false")
            _cpp_is_bool(return 42)
            ct_assert_equal(return FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("list")
        ct_add_section("Normal list")
            _cpp_is_bool(return "1;2;3")
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("List with boolean literals")
            _cpp_is_bool(return "TRUE;FALSE")
            ct_assert_equal(return FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("map")
        include(cmakepp_core/map/detail_/ctor)
        _cpp_map_ctor(my_map)
        _cpp_is_bool(result "${my_map}")
        ct_assert_equal(result FALSE)
    ct_end_section()

    ct_add_section("target")
        ct_add_section("normal target name")
            add_library(lib STATIC IMPORTED)
            _cpp_is_bool(return lib)
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("target name containing boolean literal")
            add_library(libTRUE STATIC IMPORTED)
            _cpp_is_bool(return libTRUE)
            ct_assert_equal(return FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("type")
        _cpp_is_bool(return bool)
        ct_assert_equal(return FALSE)
    ct_end_section()

ct_end_test()
