include(cmake_test/cmake_test)

ct_add_test("_cpp_is_target")
    include(cmakepp_core/types/detail_/target)

    ct_add_section("array")
        include(cmakepp_core/array/detail_/ctor)
        _cpp_array_ctor(my_array)
        _cpp_is_target(result "${my_array}")
        ct_assert_equal(result FALSE)
    ct_end_section()

    ct_add_section("bool")
        _cpp_is_target(return TRUE)
        ct_assert_equal(return FALSE)
    ct_end_section()

    ct_add_section("descriptions")
        ct_add_section("description w/o a target")
            _cpp_is_target(return "Hello World")
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("description containing a target")
            add_library(lib STATIC IMPORTED)
            _cpp_is_target(return "lib Hello World")
            ct_assert_equal(return FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("float")
        _cpp_is_target(return 3.14)
        ct_assert_equal(return FALSE)
    ct_end_section()

    ct_add_section("integer")
        _cpp_is_target(return 42)
        ct_assert_equal(return FALSE)
    ct_end_section()

    ct_add_section("list")
        ct_add_section("Normal list")
            _cpp_is_target(return "hello;world")
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("List of targets")
            add_library(lib1 STATIC IMPORTED)
            add_library(lib2 STATIC IMPORTED)
            _cpp_is_target(return "lib1;lib2")
            ct_assert_equal(return FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("map")
        include(cmakepp_core/map/detail_/ctor)
        _cpp_map_ctor(my_map)
        _cpp_is_target(result "${my_map}")
        ct_assert_equal(result FALSE)
    ct_end_section()

    ct_add_section("obj")
        include(cmakepp_core/object/detail_/ctor)
        _cpp_object_ctor(an_object)
        _cpp_is_target(result "${an_object}")
        ct_assert_equal(result FALSE)
    ct_end_section()

    ct_add_section("path")
        ct_add_section("Normal filepath (probably)")
            _cpp_is_target(return "${CMAKE_CURRENT_LIST_DIR}")
            ct_assert_equal(return FALSE)
        ct_end_section()

        ct_add_section("Contains a target")
            add_library(lib STATIC IMPORTED)
            _cpp_is_target(return "${CMAKE_CURRENT_LIST_DIR}/lib")
            ct_assert_equal(return FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("target")
        add_library(lib STATIC IMPORTED)
        _cpp_is_target(return lib)
        ct_assert_equal(return TRUE)
    ct_end_section()

    ct_add_section("type")
        _cpp_is_target(return bool)
        ct_assert_equal(return FALSE)
    ct_end_section()

ct_end_test()
