include(cmake_test/cmake_test)

ct_add_test("iterator: use case")
    include(cmakepp_core/iteration/iterator)

    ct_add_section("list")
        set(a_list 1 2 3)
        cpp_make_iterator(an_iterator "${a_list}")
        set(corr_value 1)
        while(an_iterator)
            cpp_iterator_get(elemi an_iterator)
            ct_assert_equal(elemi "${corr_value}")
            math(EXPR corr_value "${corr_value} + 1")
        endwhile()
        ct_assert_equal(corr_value 4)
    ct_end_section()
ct_end_test()
