include_guard()

include(cmakepp_core/algorithm/algorithm)
include(cmakepp_core/asserts/asserts)
include(cmakepp_core/class/class)
include(cmakepp_core/exceptions/exceptions)
include(cmakepp_core/map/map)
include(cmakepp_core/object/object)
include(cmakepp_core/serialization/serialization)
include(cmakepp_core/types/types)
include(cmakepp_core/utilities/utilities)
