include_guard()
include(cmakepp_core/object/object)
include(cmakepp_core/types/type_of)
include(cmakepp_core/utilities/call_fxn)
include(cmakepp_core/utilities/print_fxn_sig)
include(cmakepp_core/utilities/sanitize_string)

function(_cpp_object_call_guts _ocg_this _ocg_result _ocg_method)
    cpp_sanitize_string(_ocg_nice_method "${_ocg_method}")
    set(_ocg_sig "${_ocg_nice_method}")

    foreach(_ocg_arg_i "${_ocg_this}" ${ARGN})
        cpp_type_of(_ocg_type_i "${_ocg_arg_i}")
        cpp_sanitize_string(_ocg_nice_type_i "${_ocg_type_i}")
        list(APPEND _ocg_sig "${_ocg_nice_type_i}")
    endforeach()

    _cpp_object_get_symbol("${_ocg_this}" _ocg_symbol _ocg_sig)
    if(NOT _ocg_symbol)
        cpp_print_fxn_sig(_oc_str_sig ${_ocg_sig})
        message(FATAL_ERROR "No suitable overload of ${_oc_str_sig}")
    endif()
    set("${_ocg_result}" "${_ocg_symbol}" PARENT_SCOPE)
endfunction()

macro(_cpp_object_call _oc_this _oc_method)
    _cpp_object_call_guts("${_oc_this}" __oc__symbol "${_oc_method}" ${ARGN})
    cpp_call_fxn("${__oc__symbol}" "${_oc_this}" ${ARGN})
endmacro()
