include_guard()
include(cmakepp_core/object/attributes)
include(cmakepp_core/object/ctor)
include(cmakepp_core/object/serialize)
include(cmakepp_core/utilities/assert)
include(cmakepp_core/utilities/return)

function(cpp_object _o_mode _o_this)
    string(TOLOWER "${_o_mode}" _o_mode)

    if("${_o_mode}" STREQUAL "ctor")
        cpp_object_ctor("${_o_this}" ${ARGN})
        cpp_return("${_o_this}")
    elseif("${_o_mode}" STREQUAL "get_attr")
        cpp_object_get_attr("${_o_this}" "${ARGV2}" "${ARGV3}")
        cpp_return("${ARGV2}")
    elseif("${_o_mode}" STREQUAL "print")
        cpp_object_serialize("${_o_this}" _o_temp)
        message("${_o_temp}")
    elseif("${_o_mode}" STREQUAL "serialize")
        cpp_object_serialize("${_o_this}" "${ARGV2}")
        cpp_return("${ARGV2}")
    elseif("${_o_mode}" STREQUAL "set_attr")
        cpp_object_set_attr("${_o_this}" "${ARGV2}" "${ARGV3}")
    elseif("${_o_mode}" STREQUAL "_set_type")
        cpp_object_set_attr("${_o_this}" "_cpp_type" "${ARGV2}")
    elseif("${_o_mode}" STREQUAL "type")
        cpp_object_get_attr("${_o_this}" "${ARGV2}" "_cpp_type")
        cpp_return("${ARGV2}")
    else()
        cpp_assert(FALSE "Object has member function '${_o_mode}'")
    endif()
endfunction()
