include(cmake_test/cmake_test)

ct_add_test("_cpp_array_append")
    include(cmakepp_core/array/detail_/ctor)
    include(cmakepp_core/array/detail_/append)

    _cpp_array_ctor(my_array)

    ct_add_section("signature")
        set(CMAKEPP_CORE_DEBUG_MODE ON)
        ct_add_section("Arg1: array")
            _cpp_array_append(TRUE a_value)
            ct_assert_fails_as("Assertion: TRUE is array")
        ct_end_section()
    ct_end_section()

    ct_add_section("Add no values")
        _cpp_array_append("${my_array}")
        _cpp_array_length(result "${my_array}")
        ct_assert_equal(result 0)
    ct_end_section()

    ct_add_section("Add one value")
        _cpp_array_append("${my_array}" "a_value")
        _cpp_array_get(result "${my_array}" 0)
        ct_assert_equal(result "a_value")

        ct_add_section("Add a second value")
            _cpp_array_append("${my_array}" "another_value")
            _cpp_array_get(result "${my_array}" 1)
            ct_assert_equal(result "another_value")
        ct_end_section()
    ct_end_section()

    ct_add_section("Add two values")
        _cpp_array_append("${my_array}" "a_value" "another_value")
        _cpp_array_get(result "${my_array}" 0)
        ct_assert_equal(result "a_value")
        _cpp_array_get(result "${my_array}" 1)
        ct_assert_equal(result "another_value")
    ct_end_section()
ct_end_test()
