include_guard()
include(cmakepp_core/object/object)

function(cpp_overload_is_variadic _oiv_this _oiv_is_variadic)
    cpp_object(GET_ATTR "${_oiv_this}" _oiv_args "args")
    list(FIND _oiv_args "args" "${_oiv_is_variadic}")
    if("${${_oiv_is_variadic}}" EQUAL -1)
        set("${_oiv_is_variadic}" FALSE PARENT_SCOPE)
    else()
        set("${_oiv_is_variadic}" TRUE PARENT_SCOPE)
    endif()
endfunction()
