include_guard()
include(cmakepp_core/object/object)
include(cmakepp_core/overload/is_variadic)
include(cmakepp_core/utilities/return)

function(cpp_overload_n_required _onr_this _onr_n_required)

    cpp_object(GET_ATTR "${_onr_this}" _onr_args "args")
    list(LENGTH _onr_args "${_onr_n_required}")
    cpp_overload_is_variadic("${_onr_this}" _onr_is_variadic)
    if("${_onr_is_variadic}")
        math(EXPR "${_onr_n_required}" "${${_onr_n_required}} - 1")
    endif()
    cpp_return("${_onr_n_required}")
endfunction()
