include_guard()
include(cmakepp_core/overload/ctor)
include(cmakepp_core/overload/is_match)
include(cmakepp_core/overload/is_variadic)
include(cmakepp_core/overload/n_required)
include(cmakepp_core/utilities/return)

function(cpp_overload _o_method _o_this)

    string(TOLOWER "${_o_method}" _o_method)
    if("${_o_method}" STREQUAL "args")
        cpp_object(GET_ATTR "${_o_this}" "${ARGV2}" "args")
        cpp_return("${ARGV2}")
    elseif("${_o_method}" STREQUAL "ctor")
        cpp_overload_ctor("${_o_this}" ${ARGN})
        cpp_return("${_o_this}")
    elseif("${_o_method}" STREQUAL "is_match")
        cpp_overload_is_match("${_o_this}" ${ARGN})
        cpp_return("${ARGV2}")
    elseif("${_o_method}" STREQUAL "is_variadic")
        cpp_overload_is_variadic("${_o_this}" "${ARGV2}")
        cpp_return("${ARGV2}")
    elseif("${_o_method}" STREQUAL "n_required")
        cpp_overload_n_required("${_o_this}" "${ARGV2}")
        cpp_return("${ARGV2}")
    elseif("${_o_method}" STREQUAL "required_args")
        cpp_overload_n_required("${_o_this}" _o_nargs)
        cpp_object(GET_ATTR "${_o_this}" _o_args "args")
        list(SUBLIST _o_args 0 "${_o_nargs}" "${ARGV2}")
        cpp_return("${ARGV2}")
    else()
        message(
           FATAL_ERROR
           "Class Overload does not have member/attribute '${_o_method}'."
        )
    endif()
endfunction()
