include(cmake_test/cmake_test)

ct_add_test("_cpp_map_merge")
    include(cmakepp_core/algorithm/equal)
    include(cmakepp_core/map/map)

    ct_add_section("Two empty maps")
        cpp_map(CTOR lhs)
        cpp_map(CTOR rhs)
        _cpp_map_merge("${lhs}" "${rhs}")
        cpp_equal(result "${lhs}" "${rhs}")
        ct_assert_equal(result TRUE)
    ct_end_section()

    ct_add_section("Merge into empty")
        cpp_map(CTOR lhs)
        cpp_map(CTOR rhs a_key a_value foo bar)
        _cpp_map_merge("${lhs}" "${rhs}")
        cpp_equal(result "${lhs}" "${rhs}")
        ct_assert_equal(result TRUE)
    ct_end_section()

    ct_add_section("Merge empty into full")
        cpp_map(CTOR lhs)
        cpp_map(CTOR rhs a_key a_value foo bar)
        cpp_map(CTOR corr a_key a_value foo bar)
        _cpp_map_merge("${rhs}" "${lhs}")
        cpp_equal(result "${rhs}" "${corr}")
        ct_assert_equal(result TRUE)
    ct_end_section()

    ct_add_section("Merge two disjoint maps")
        cpp_map(CTOR lhs 2 42 5 TRUE)
        cpp_map(CTOR rhs a_key a_value foo bar)
        cpp_map(CTOR corr a_key a_value foo bar 2 42 5 TRUE)

        ct_add_section("rhs into lhs")
            _cpp_map_merge("${lhs}" "${rhs}")
            cpp_equal(result "${lhs}" "${corr}")
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("lhs into rhs")
            _cpp_map_merge("${rhs}" "${lhs}")
            cpp_equal(result "${rhs}" "${corr}")
            ct_assert_equal(result TRUE)
        ct_end_section()
    ct_end_section()

    ct_add_section("Merge intersecting maps")
        cpp_map(CTOR lhs 2 42 foo TRUE)
        cpp_map(CTOR rhs a_key a_value foo bar)

        ct_add_section("rhs into lhs")
            cpp_map(CTOR corr a_key a_value foo bar 2 42)
            _cpp_map_merge("${lhs}" "${rhs}")
            cpp_equal(result "${lhs}" "${corr}")
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("lhs into rhs")
            cpp_map(CTOR corr a_key a_value TRUE 2 42)
            _cpp_map_merge("${rhs}" "${lhs}")
            cpp_equal(result "${rhs}" "${corr}")
            ct_assert_equal(result TRUE)
        ct_end_section()
    ct_end_section()
ct_end_test()
