include_guard()

function(_cpp_mangle_fxn_sig _cmfs_result _cmfs_type)
    set("${_cmfs_result}" "${_cmfs_type}")
    foreach(_cmfs_type_i ${ARGN})
        set("${_cmfs_result}" "${${_cmfs_result}}_${cmfs_type_i}")
    endforeach()
    cpp_return("${_cmfs_result}")
endfunction()

function(_cpp_add_member _cam_type _cam_fxn_name _cam_file)
    _cpp_get_class_registry(_cam_reg)
    cpp_map(GET _cam_type_map "${_cam_reg}" "${_cam_type}")
    _cpp_mangle_fxn_sig(_cam_sig "${_cam_type}" ${ARGN})
    cpp_map(APPEND "${_cam_type_map}" "${_cam_fxn_name}" "${_cam_sig}")
endfunction()

macro(_cpp_member _cm_name _cm_type)
    _cpp_add_member("${_cm_type}" "${_cm_name}" "${CMAKE_CURRENT_LIST_FILE}")
endmacro()
