include_guard()

function(_cpp_class_write_overloads _ccwo_result _ccwo_type)
    _cpp_class_get_fxns(_ccwo_fxns "${_ccwo_type}")
    cpp_map(KEYS _ccwo_keys "${_ccwo_fxns}")
    foreach(_ccwo_fxn_i ${_ccwo_keys})
        cpp_map(GET _ccwo_overloads "${_ccwo_fxns}" "${_ccwo_fxn_i}")
        cpp_array(END _ccwo_end "${_ccwo_overloads}")
        foreach(_ccwo_j RANGE "${_ccwo_end}")
            cpp_array(GET _ccwo_overload_j "${_ccwo_overloads}" "${_ccwo_j}")
            set(_ccwo_cond "\n    elseif(\"\${__${_ccwo_type}_mn}\" STREQUAL ")
            set(_ccwo_cond "${_ccwo_cond}\"${_ccwo_overload_j}\")\n")
            set(_ccwo_cond "${_ccwo_cond}        ${_ccwo_overload_j}(\${ARGN})")
            set("${_ccwo_result}" "${${_ccwo_result}}${_ccwo_cond}")
        endforeach()
    endforeach()
    cpp_return("${_ccwo_result}")
endfunction()
