include(cmake_test/cmake_test)

ct_add_test("_cpp_object_merge")
    include(cmakepp_core/object/detail_/add_base)
    include(cmakepp_core/object/detail_/add_function)
    include(cmakepp_core/object/detail_/ctor)
    include(cmakepp_core/object/detail_/equal)
    include(cmakepp_core/object/detail_/merge)
    include(cmakepp_core/object/detail_/print)
    include(cmakepp_core/object/detail_/set_attr)

    _cpp_object_ctor(default_object)
    _cpp_object_ctor(non_default)
    _cpp_object_add_base("${non_default}" a_base)
    _cpp_object_add_function("${non_default}" a_fxn a_base)
    _cpp_object_set_attr("${non_default}" foo bar)

    ct_add_section("Signature")
        set(CMAKEPP_CORE_DEBUG_MODE ON)

        ct_add_section("Arg0 must be obj")
            _cpp_object_merge(TRUE "${default_object}")
            ct_assert_fails_as("Assertion: TRUE is obj")
        ct_end_section()

        ct_add_section("Arg1 must be obj")
            _cpp_object_merge("${default_object}" TRUE)
            ct_assert_fails_as("Assertion: TRUE is obj")
        ct_end_section()

        ct_add_section("Takes 2 arguments")
            _cpp_object_merge("${default_object}" "${default_object}" hello)
            ct_assert_fails_as("Function takes 2 argument(s), but 3 was/were")
        ct_end_section()
    ct_end_section()

    ct_add_section("Merge default into default")
        _cpp_object_merge("${default_object}" "${default_object}")
        _cpp_object_ctor(another_default)
        _cpp_object_equal("${default_object}" result "${another_default}")
        ct_assert_equal(result TRUE)
    ct_end_section()

    ct_add_section("Merge non-default into default")
        _cpp_object_merge("${default_object}" "${non_default}")
        _cpp_object_equal("${non_default}" result "${default_object}")
        ct_assert_equal(result TRUE)
    ct_end_section()

    ct_add_section("Merge default into non-default")
        _cpp_object_merge("${non_default}" "${default_object}")
        _cpp_object_ctor(corr)
        _cpp_object_add_base("${corr}" a_base)
        _cpp_object_add_function("${corr}" a_fxn a_base)
        _cpp_object_set_attr("${corr}" foo bar)
        _cpp_object_equal("${corr}" result "${non_default}")
    ct_end_section()

    ct_add_section("Disjoint non-default classes")
        _cpp_object_ctor(other)
        _cpp_object_add_base("${other}" another_base)
        _cpp_object_add_function("${other}" another_fxn another_base)
        _cpp_object_set_attr("${other}" hello world)

        ct_add_section("Other into non_default")
            _cpp_object_ctor(corr)
            _cpp_object_add_base("${corr}" a_base)
            _cpp_object_add_base("${corr}" another_base)
            _cpp_object_add_function("${corr}" a_fxn a_base)
            _cpp_object_add_function("${corr}" another_fxn another_base)
            _cpp_object_set_attr("${corr}" foo bar)
            _cpp_object_set_attr("${corr}" hello world)

           _cpp_object_merge("${non_default}" "${other}")
           _cpp_object_equal("${corr}" result "${non_default}")
           ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("Non_default into other")
            _cpp_object_ctor(corr)
            _cpp_object_add_base("${corr}" another_base)
            _cpp_object_add_base("${corr}" a_base)
            _cpp_object_add_function("${corr}" a_fxn a_base)
            _cpp_object_add_function("${corr}" another_fxn another_base)
            _cpp_object_set_attr("${corr}" foo bar)
            _cpp_object_set_attr("${corr}" hello world)

            _cpp_object_merge("${other}" "${non_default}")
            _cpp_object_equal("${corr}" result "${other}")
            ct_assert_equal(result TRUE)
        ct_end_section()

    ct_end_section()

    ct_add_section("Common function")
        _cpp_object_ctor(other)
        _cpp_object_add_base("${other}" another_base)
        _cpp_object_add_function("${other}" a_fxn a_third_base)
        _cpp_object_add_function("${other}" another_fxn another_base)
        _cpp_object_set_attr("${other}" hello world)

        ct_add_section("Other into non_default")
            _cpp_object_ctor(corr)
            _cpp_object_add_base("${corr}" a_base)
            _cpp_object_add_base("${corr}" another_base)
            _cpp_object_add_function("${corr}" a_fxn a_base)
            _cpp_object_add_function("${corr}" another_fxn another_base)
            _cpp_object_set_attr("${corr}" foo bar)
            _cpp_object_set_attr("${corr}" hello world)

            _cpp_object_merge("${non_default}" "${other}")
            _cpp_object_equal("${corr}" result "${non_default}")
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("Non_default into other")
            _cpp_object_ctor(corr)
            _cpp_object_add_base("${corr}" another_base)
            _cpp_object_add_base("${corr}" a_base)
            _cpp_object_add_function("${corr}" a_fxn a_third_base)
            _cpp_object_add_function("${corr}" another_fxn another_base)
            _cpp_object_set_attr("${corr}" foo bar)
            _cpp_object_set_attr("${corr}" hello world)

            _cpp_object_merge("${other}" "${non_default}")
            _cpp_object_equal("${corr}" result "${other}")
            ct_assert_equal(result TRUE)
        ct_end_section()

    ct_end_section()

    ct_add_section("Common attribute")
        _cpp_object_ctor(other)
        _cpp_object_add_base("${other}" another_base)
        _cpp_object_add_function("${other}" a_fxn a_base)
        _cpp_object_add_function("${other}" another_fxn another_base)
        _cpp_object_set_attr("${other}" hello world)
        _cpp_object_set_attr("${other}" foo 42)

        ct_add_section("Other into non_default")
            _cpp_object_ctor(corr)
            _cpp_object_add_base("${corr}" a_base)
            _cpp_object_add_base("${corr}" another_base)
            _cpp_object_add_function("${corr}" a_fxn a_base)
            _cpp_object_add_function("${corr}" another_fxn another_base)
            _cpp_object_set_attr("${corr}" foo 42)
            _cpp_object_set_attr("${corr}" hello world)

            _cpp_object_merge("${non_default}" "${other}")
            _cpp_object_equal("${corr}" result "${non_default}")
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("Non_default into other")
            _cpp_object_ctor(corr)
            _cpp_object_add_base("${corr}" another_base)
            _cpp_object_add_base("${corr}" a_base)
            _cpp_object_add_function("${corr}" a_fxn a_base)
            _cpp_object_add_function("${corr}" another_fxn another_base)
            _cpp_object_set_attr("${corr}" foo bar)
            _cpp_object_set_attr("${corr}" hello world)

            _cpp_object_merge("${other}" "${non_default}")
            _cpp_object_equal("${corr}" result "${other}")
            ct_assert_equal(result TRUE)
        ct_end_section()

    ct_end_section()


ct_end_test()
