include_guard()
include(cmakepp_core/map/map)
include(cmakepp_core/serialization/detail_/serialize_value)

function(_cpp_serialize_map _sm_return _sm_value)

    cpp_map(KEYS "${_sm_value}" _sm_keys)
    set(_sm_temp "{")
    list(LENGTH _sm_keys _sm_n_keys)
    set(_sm_counter 0)
    foreach(_sm_key_i ${_sm_keys})
        cpp_map(GET "${_sm_value}" _sm_value_i "${_sm_key_i}")
        _cpp_serialize_value(_sm_serial_key "${_sm_key_i}")
        _cpp_serialize_value(_sm_serial_value "${_sm_value_i}")
        string(APPEND _sm_temp " ${_sm_serial_key} : ${_sm_serial_value}")
        math(EXPR _sm_counter "${_sm_counter} + 1")
        if("${_sm_counter}" LESS "${_sm_n_keys}")
            string(APPEND _sm_temp ",")
        endif()
    endforeach()
    string(APPEND _sm_temp " }")
    set("${_sm_return}" "${_sm_temp}" PARENT_SCOPE)
endfunction()
