include_guard()
include(cmakepp_core/map/detail_/are_equal)
include(cmakepp_core/map/detail_/ctor)
include(cmakepp_core/map/detail_/get)
include(cmakepp_core/map/detail_/has_key)
include(cmakepp_core/map/detail_/keys)
include(cmakepp_core/map/detail_/set)

macro(cpp_map _cm_mode)
    string(TOUPPER "${_cm_mode}" __cm_mode)
    if("${_cm_mode}" STREQUAL "APPEND")
        _cpp_map_append(${ARGN})
    elseif("${_cm_mode}" STREQUAL "ARE_EQUAL")
        _cpp_map_are_equal(${ARGN})
    elseif("${__cm_mode}" STREQUAL "CTOR")
        _cpp_map_ctor(${ARGN})
    elseif("${__cm_mode}" STREQUAL "GET")
        _cpp_map_get(${ARGN})
    elseif("${__cm_mode}" STREQUAL "HAS_KEY")
        _cpp_map_has_key(${ARGN})
    elseif("${__cm_mode}" STREQUAL "KEYS")
        _cpp_map_keys(${ARGN})
    elseif("${__cm_mode}" STREQUAL "SET")
        _cpp_map_set(${ARGN})
    else()
        message(FATAL_ERROR "Unrecognized map member function: ${_cm_mode}.")
    endif()
endmacro()
