include_guard()
include(cmakepp_core/map/detail_/ctor)
include(cmakepp_core/map/detail_/has_key)

macro(cpp_map _cm_mode)
    string(TOUPPER "${_cm_mode}" _cm_mode)
    if("${_cm_mode}" STREQUAL "CTOR")
        _cpp_map_ctor(${ARGN})
    elseif("${_cm_mode}" STREQUAL "HAS_KEY")
        _cpp_map_has_key(${ARGN})
    else()
        message(FATAL_ERROR "Unrecognized map member function: ${_cm_mode}.")
    endif()
endmacro()
