include(cmake_test/cmake_test)

ct_add_test("cpp_equal")
    include(cmakepp_core/algorithm/equal)

    ct_add_section("Different Types")
        cpp_equal(result TRUE 1)
        ct_assert_equal(result FALSE)
    ct_end_section()

    ct_add_section("array")
        include(cmakepp_core/array/array)
        cpp_array(CTOR lhs 1 2 3)

        ct_add_section("LHS == RHS")
            cpp_array(CTOR rhs 1 2 3)
            cpp_equal(result "${lhs}" "${rhs}")
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("LHS != RHS")
            cpp_array(CTOR rhs 4 5 6)
            cpp_equal(result "${lhs}" "${rhs}")
            ct_assert_equal(result FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("bool")
        ct_add_section("LHS == RHS")
            cpp_equal(result TRUE TRUE)
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("LHS != RHS")
            cpp_equal(result TRUE FALSE)
            ct_assert_equal(result FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("code")
        ct_add_section("LHS == RHS")
            cpp_equal(result [[${LHS}]] [[${LHS}]])
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("LHS != RHS")
            set(LHS TRUE)
            set(RHS FALSE)
            cpp_equal(result [[${LHS}]] [[${RHS}]])
        ct_end_section()
    ct_end_section()

    ct_add_section("descriptions")
        ct_add_section("LHS == RHS")
            cpp_equal(result "Hello World" "Hello World")
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("LHS != RHS")
            cpp_equal(result "Hello World" "foo bar")
            ct_assert_equal(result FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("floats")
        ct_add_section("LHS == RHS")
            cpp_equal(result "3.14" "3.14")
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("LHS != RHS")
            cpp_equal(result "3.14" "1.23")
            ct_assert_equal(result FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("ints")
        ct_add_section("LHS == RHS")
            cpp_equal(result 42 42)
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("LHS != RHS")
            cpp_equal(result 42 84)
            ct_assert_equal(result FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("lists")
        ct_add_section("LHS == RHS")
            cpp_equal(result "Hello;World" "Hello;World")
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("LHS != RHS")
            cpp_equal(result "Hello;World" "Hello;bar")
            ct_assert_equal(result FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("map")
        include(cmakepp_core/map/map)
        cpp_map(CTOR lhs)
        cpp_map(CTOR rhs)
        cpp_map(SET "${lhs}" a_key hello)
        cpp_map(SET "${lhs}" another_key world)

        ct_add_section("LHS == RHS")
            cpp_map(SET "${rhs}" a_key hello)
            cpp_map(SET "${rhs}" another_key world)
            cpp_equal(result "${lhs}" "${rhs}")
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("LHS != RHS")
            cpp_equal(result "${lhs}" "${rhs}")
            ct_assert_equal(result FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("targets")
        ct_add_section("LHS == RHS")
            add_library(a_lib STATIC IMPORTED)
            cpp_equal(result a_lib a_lib)
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("LHS != RHS")
            add_library(lhs STATIC IMPORTED)
            add_library(rhs STATIC IMPORTED)
            cpp_equal(result lhs rhs)
            ct_assert_equal(result FALSE)
        ct_end_section()
    ct_end_section()

    ct_add_section("types")
        ct_add_section("LHS == RHS")
            cpp_equal(result int int)
            ct_assert_equal(result TRUE)
        ct_end_section()

        ct_add_section("LHS != RHS")
            cpp_equal(result int bool)
            ct_assert_equal(result FALSE)
        ct_end_section()
    ct_end_section()
ct_end_test()
