name: CMakePPLang Documentation Test
on:
  pull_request:
    branches:
      - master
jobs:
  docs_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
