name: CMakePPLang Unit Tests
on:
  pull_request:
    branches:
      - master
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake: [3.19, latest, latestrc]
    env:
      cmake_version: ${{ matrix.cmake }}
      os: Linux-x86_64
    steps:
      - uses: actions/checkout@v1

#       - name: get cmake
#         env:
#           url_prefix: https://github.com/Kitware/CMake/releases/download
#         run: |
#           cmake_script=cmake-${cmake_version}-${os}.sh
#           wget "${url_prefix}/v${cmake_version}/${cmake_script}"
#           yes | /bin/sh "${cmake_script}"

      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ env.cmake_version }}

      - name: Check CMake and CTest Versions
        run: |
          cmake --version
          ctest --version

      - name: configure
        run: |
          cmake -H. -Bbuild -DBUILD_TESTING=ON

      - name: unit_test
        run: |
          cd build
          ctest -j 2 --output-on-failure
